name: Build axon-argocd

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ArgoCD using Melange
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read
      security-events: write

    steps:
    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
        echo ::set-output name=epoch::$(date -u +%s)
      shell: bash

    - uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Install qemu-user
      run: sudo apt-get install -y qemu-user

    - uses: sigstore/cosign-installer@main

    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: melange.yaml
        sign-with-temporary-key: true
        archs: x86_64,aarch64
